[build]
  base = "invoice-app" 
  command = "pnpm run build"
  publish = "invoice-app/dist"
  functions = "netlify/functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200